Tox/Zuul: Set pep8 job node to debian bullseye
importlib_metadata, a dependency for building python pkgs,
received changes where some of its API is deprecated [1],
causing the error:

AttributeError: 'EntryPoints' object has no attribute 'get'

A possible fix is to clip the version to below 5.0,
but the debian-bullseye Zuul node already provides a compatible
version, with the added advantage of being the base OS
used for STX, increasing reliability for the tests.

Refs:
[1] https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

Test Plan:
pass - In a debian:bullseye container, run:
       tox -epep8 -c nfv/tox.ini

Closes-Bug: 2090865

Change-Id: I7211277f1484e7103b8dc48eb74693e3713f7caa
Signed-off-by: Leonardo Fagundes Luz Serrano <Leonardo.FagundesLuzSerrano@windriver.com>